export const COUNTRIES = [
  { value: 'CA', label: 'Canada' },
  { value: 'US', label: 'US' },
  { value: 'UK', label: 'UK' },
  { value: 'IN', label: 'India' },
  { value: 'ES', label: 'Spain' },
];

export const ROLES = [
  { value: 'consultant', label: 'Consultant' },
  { value: 'customer-service', label: 'Customer Service' },
  { value: 'engineering', label: 'Engineering' },
  { value: 'investor-analyst', label: 'Investor / Analyst' },
  { value: 'maintenance-reliability', label: 'Maintenance / Reliability' },
  { value: 'operations-supply-chain', label: 'Operations / Supply Chain' },
  { value: 'owner-operator-general-management', label: 'Owner / Operator / General Management' },
  { value: 'project-management', label: 'Project Management' },
  { value: 'purchasing-procurement', label: 'Purchasing / Procurement' },
  { value: 'quality', label: 'Quality' },
  { value: 'sales-marketing', label: 'Sales / Marketing' },
  { value: 'student-professor', label: 'Student / Professor' },
  { value: 'other', label: 'Other' },
];

export const INDUSTRIES = [
  { value: 'aggregate-cement', label: 'Aggregate / Cement' },
  { value: 'agriculture', label: 'Agriculture' },
  { value: 'automation-robotics', label: 'Automation / Robotics' },
  { value: 'automotive', label: 'Automotive' },
  { value: 'bfsi', label: 'BFSI' },
  { value: 'commercial-trucks-buses', label: 'Commercial Trucks & Buses' },
  { value: 'construction', label: 'Construction' },
  { value: 'conveyors', label: 'Conveyors' },
  { value: 'customer-service', label: 'Customer Service' },
  { value: 'electric-motors', label: 'Electric Motors' },
  { value: 'fans-blowers-hvac', label: 'Fans / Blowers / HVAC' },
  { value: 'fashion', label: 'Fashion' },
  { value: 'food-beverage', label: 'Food & Beverage' },
  { value: 'forest-paper', label: 'Forest & Paper' },
  { value: 'forklifts', label: 'Forklifts' },
  { value: 'fossil-energy', label: 'Fossil Energy (oil/gas/coal)' },
  { value: 'gear-drives', label: 'Gear Drives' },
  { value: 'general-industry', label: 'General Industry' },
  { value: 'government-agencies', label: 'Government Agencies' },
  { value: 'healthcare', label: 'Healthcare' },
  { value: 'hydraulics', label: 'Hydraulics' },
  { value: 'it', label: 'IT' },
  { value: 'machine-tool', label: 'Machine Tool' },
  { value: 'marine', label: 'Marine' },
  { value: 'metals', label: 'Metals' },
  { value: 'mining', label: 'Mining' },
  { value: 'printing', label: 'Printing' },
  { value: 'pumps-compressors', label: 'Pumps & Compressors' },
  { value: 'rail', label: 'Rail' },
  { value: 'recreational-vehicles', label: 'Recreational Vehicles' },
  { value: 'solar-energy', label: 'Solar Energy' },
  { value: 'textile', label: 'Textile' },
  { value: 'wastewater-treatment', label: 'Wastewater Treatment' },
  { value: 'wind-energy', label: 'Wind Energy' },
  { value: 'other', label: 'Other' },
];

export const CTA_BACKGROUND = "/images/cta/cta-bg.png";

